### ISSUE TITLE
Is the link provided here correct?

### ISSUE THREAD

**Issue by GellmanSparrowS** [lamm-mit/GraphGeneration#1]
Here's the link I found:
git clone https://github.com/lamm-mit/HierarchicalDesign/
and i can't find GraphGeneration in there.

**Comment by lamm-mit** [comment]
It should work now, please let us know. Thank you for your interest in our work.

**Comment by lamm-mit** [comment]
Dear Yunhao

Thanks for reaching out. I fixed the repo and updated the codes.

Markus

From: Yunhao Yang ***@***.***>
Sent: Wednesday, July 19, 2023 11:28 AM
To: lamm-mit/GraphGeneration ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lamm-mit/GraphGeneration] Is the link provided here correct? (Issue #1)


Here's the link I found:
git clone https://github.com/lamm-mit/HierarchicalDesign/
and i can't find GraphGeneration in there.

**Comment by GellmanSparrowS** [comment]
Yes, the code does get fixed, it is very interesting work, thank you for your help.
